### ISSUE TITLE
feat: refactor the `Withdrawal Pending List`

### ISSUE THREAD

**Issue by Flouse** [godwokenrises/light-godwoken#171]
After sending a withdrawal_request, the `Withdrawal Pending List` took about 5 minutes to display the new pending withdrawal.
It would be better to show the status of the new pending withdrawal as soon as possible.

![image](https://user-images.githubusercontent.com/1297478/181151674-6644e057-99eb-4b96-a5b2-ae6cad6139f4.png)

## Suggested solution
We could use `gw_get_withdrawal` RPC to get the status of a new withdrawal request.
```bash
echo '{
    "id": 2,
    "jsonrpc": "2.0",
    "method": "gw_get_withdrawal",
    "params": ["Withdrawal Tx HASH"]
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://godwoken-testnet-v1.ckbapp.dev
```

**Comment by Dawn-githup** [comment]
![image](https://user-images.githubusercontent.com/77844990/211705967-e33c2e12-c052-4585-8d89-f1241fce4e24.png)

Use gw_ get_  With draws the status of the new withdrawal request obtained by RPC. If there is no timestamp field, the unlock extraction time will not be displayed?

**Comment by ShookLyngs** [comment]
> use gw_get_withdrawal RPC to get the status of a new withdrawal request. If there is no timestamp field, the unlock extraction time will not be displayed?

Currently, we use `block_number` field from the api to calculate the estimated time.

**Comment by Flouse** [comment]
Maybe we could make it simpler.
If the result from `gw_get_withdrawal` RPC containing `"status":"committed"`, then we could just show the withdrawal in the `Withdrawal Pending List` with `committed` status.
And then later when we can update the `estimated time` when `withdrawal_histories API` provides more info.
