### ISSUE TITLE
Feature request: withdrawal from L1 Wallet address to other L1 addresses (CEXs, wallets, etc)

### ISSUE THREAD

**Issue by alejandroRbit** [godwokenrises/light-godwoken#189]
Currently a user who uses https://bridge.godwoken.io/ to perform the withdrawal from L2 to L1 has to use YokaiSwap (https://v1.yokaiswap.com/bridge/transfer) or another third-party app to send from L1 Wallet address to a deposit address of a CEX or their Wallet (PortalWallet, Neuron, etc). In my opinion, users should be able to do all the withdrawal steps, including sending to their CEX or wallet or other L1 address from the public architecture and not depend on third parties/apps. It also involves an extra step (change app), which decreases the user experience. I wonder if it is possible to add this functionality to the bridge.

In this way we could avoid this:

![Screenshot_20220916-180326_Telegram](https://user-images.githubusercontent.com/94946624/190682266-cc53ba30-1b01-42ac-8b48-361be0c8f288.jpg)

Thank you!

**Comment by Flouse** [comment]
## New features to be discussed
- [ ] Add Layer1 transfer feature on Godwoken Bridge UI

**Comment by Flouse** [comment]
Hi, @alejandroRbit 
Thank you for the advice.

![image](https://user-images.githubusercontent.com/1297478/199676563-fec71b04-b5bf-4a36-ae44-c7fe2d8ea7ee.png)
[Godwoken Bridge](https://bridge.godwoken.io/) now supports layer1 transfer.
