### ISSUE TITLE
The transaction returned by the Withdraw request hx stays permanently

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#193]
## **Describe the bug**
The transaction returned by the Withdraw request hx stays permanently

1. Initiate a withdrawal
2. return transaction hx

![image](https://user-images.githubusercontent.com/77844990/191481223-076a4332-b398-4527-aac3-99c32339b58f.png)

expect
> Can be set to not stay permanently

**Comment by ShookLyngs** [comment]
The core issue here is that withdrawals don't appear on the list instantly after the submission, I will try to resolve it in another issue, therefore closing this one as the notification is not what we need to resolve.
