### ISSUE TITLE
L1 has no ckb, and Get Test Token (TTKN) on L1 has no prompt

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#194]
## **Describe the bug**
L1 has no ckb, and Get Test Token (TTKN) on L1 has no prompt

1. L1 has no ckb
2. Get Test Token

![image](https://user-images.githubusercontent.com/77844990/191655873-4f6f108b-6055-4cd1-b9ec-3d32d462f099.png)

expect
> Give corresponding prompt information

**Comment by GitOfJason** [comment]
@Dawn-githup  The issue cannot be repeated

https://user-images.githubusercontent.com/124339951/217744807-dc503713-030c-40b2-915a-ff43ea48ed34.mov
