### ISSUE TITLE
'Get 1000 Test Token (TTKN) on L1' Data duplication error occurs after two consecutive operations

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#197]
## **Describe the bug**
'Get 1000 Test Token (TTKN) on L1' Data duplication error occurs after two consecutive operations

1. "Get 1000 Test Tokens (TTKN) on L1" twice in a row

> Error prompt appears
```
 JSONRPCError: server error {"code":-1107,"message":"PoolRejectedDuplicatedTransaction: Transaction(Byte32(0xe233d9171f944bd43e145cf98d45f19e6c03483112a0338323e62632fcc42690)) already exist in transaction_pool","data":"Duplicated(Byte32(0xe233d9171f944bd43e145cf98d45f19e6c03483112a0338323e62632fcc42690))"}
```

**Comment by GitOfJason** [comment]
I think that this is a normal error, because it is not allowed to create two identical transactions.  What we need to do is to provide users with friendly error prompts when errors occur.
@Flouse @ShookLyngs

**Comment by Flouse** [comment]
> provide users with friendly error prompts when errors occur.

yes, LGTM.

and, do you think a retry mechanism is appropriate in this case.

**Comment by GitOfJason** [comment]
> > provide users with friendly error prompts when errors occur.
> 
> yes, LGTM.
> 
> and, do you think a retry mechanism is appropriate in this case?
> 
> * retry after 10s if the transaction is failed
> * up to 3 times

Use simple prompts for the moment to avoid more complexity
