### ISSUE TITLE
Request change [Estimated time left] of a normal withdrawal

### ISSUE THREAD

**Issue by alejandroRbit** [godwokenrises/light-godwoken#220]
When making a withdrawal to L1 from Godwoken Bridge, the default time is always 7 days. But in practice it is usually longer, around 10 days.

![Screenshot_20221105-161701_Discord](https://user-images.githubusercontent.com/94946624/200126927-51b642be-2476-4434-a9c6-9cc12516060d.jpg)

In the Godwoken documentation (https://docs.godwoken.io/gwchangelog/v0difv1) there is a remaining time interval between 8 and 12 days, depending on the status of the network.

Some ideas:

- Show as estimated remaining time the minimum possible, 8 days + third proposal.

- Show as estimated remaining time the average time between 8 and 12, which would be 10 days + third proposal.

- Introduce a textbox that informs the user that the remaining time is variable and not fixed and therefore it can take between 8/12 days. Inside [Pending], for example.

![Screenshot_20221105-161433_MetaMask](https://user-images.githubusercontent.com/94946624/200126850-5aab3f18-3beb-4640-ac57-7793c3016803.jpg)

Thank you!

**Comment by ShookLyngs** [comment]
Yes, the time left is `estimated` so the finalized time is not guaranteed.
I agree with you that it would be better to add more friendly text to explain the concept of `estimated time`.

@Flouse What do you think?

**Comment by alejandroRbit** [comment]
The sign "~" could also be added in front of the estimated time to reinforce the message.

**Comment by Gridzilla** [comment]
The initial withdrawal window suggests 7 days as the estimated withdrawal time, already in contradiction with the Godwoken docs 8-12 days. 
![image](https://user-images.githubusercontent.com/4488015/200128968-c9bf7409-a5a2-41ce-87b9-f329b9ab5224.png)

And a freshly started withdrawal displays this estimate:
![image](https://user-images.githubusercontent.com/4488015/200129331-bf7eb928-f5b1-41e9-90f7-dea701dd1239.png)

Again 7 days. I doubt adding more text and a ~ tilde sign will improve user experience. Can't the estimate be tied to a rolling average block time? It seems it is now semi-fixed to 7 days and then just runs like a clock that's constantly late.

**Comment by Flouse** [comment]
Thanks for the feedbacks.
> In the v1 network, the withdrawal time is adjusted to 8 ~ 12 days, which depends on the network status. This gives more time for layer2 verification and challenge.
> https://docs.godwoken.io/gwchangelog/v0difv1#withdrawal-time

## TODO
1. Next week, Godwoken mainnet_v1 plans to upgrade to v1.7.0, which will make the average_block_time of Godwoken more stable (~45s).

2. We will adjust the "estimated time" display logic too. @ShookLyngs 
   Thanks @alejandroRbit for the suggestion.

**Comment by Flouse** [comment]
Hello @alejandroRbit , Godwoken Bridge has just released version 0.3.2, and one of the the major changes:

### Provides more accurate estimated withdrawal time
We have updated the average block produce time on Godwoken Bridge so the estimated withdrawal time left is displayed more accurately. 

## References
- https://github.com/godwokenrises/light-godwoken/pull/234
- https://github.com/godwokenrises/light-godwoken/releases/tag/0.3.2
