### ISSUE TITLE
Bug: Request withdrawal does not appear in pending.

### ISSUE THREAD

**Issue by alejandroRbit** [godwokenrises/light-godwoken#239]
A user has reported a strange issue. He had four request withdrawals with active countdowns, and today one of them, the last one, has disappeared. He can't see it in either YokaiSwap or Godwoken Bridge.

Looking how to reproduce the problem, I have made several test request withdrawals with 400 CKB through https://bridge.godwoken.io/ and they do not appear in pending, but the 400 CKB disappear from the L2 balance. The user has also done it to test it and the same thing happens to him.

![Screenshot_20221201-190421_MetaMask](https://user-images.githubusercontent.com/94946624/205128528-1bba20ab-448a-4a30-9790-f02b8915b828.jpg)

![Screenshot_20221201-190626_MetaMask](https://user-images.githubusercontent.com/94946624/205128562-27924011-a752-4084-b0e3-9821e5d44da3.jpg)

**Comment by alejandroRbit** [comment]
Also, using Godwoken explorer, when the user accesses the Bridged Transfer page associated with his address, it has not been updated for three days and he has made deposits in that time frame.

![IMG_4512-1](https://user-images.githubusercontent.com/94946624/205150568-010881a9-95c6-4c2e-b161-66ac9e235822.jpg)

**Comment by Flouse** [comment]
> Looking how to reproduce the problem, I have made several test request withdrawals with 400 CKB through https://bridge.godwoken.io/ and they do not appear in pending, but the 400 CKB disappear from the L2 balance. The user has also done it to test it and the same thing happens to him.

related issue:
- https://github.com/godwokenrises/light-godwoken/issues/171

**Comment by Flouse** [comment]
> Also, using Godwoken explorer, when the user accesses the Bridged Transfer page associated with his address, it has not been updated for three days and he has made deposits in that time frame.

Could you send me the address privately through Discord DM?
we want to analysis the asset history of the address.

**Comment by Flouse** [comment]
## Related issues
- https://github.com/Magickbase/godwoken_explorer/issues/1187

**Comment by alejandroRbit** [comment]
> > Also, using Godwoken explorer, when the user accesses the Bridged Transfer page associated with his address, it has not been updated for three days and he has made deposits in that time frame.
> 
> @alejandroRbit Could you send me the address privately through Discord DM? we want to analysis the asset history of the address.

Update: It seems that the measures that have been taken have fixed all the problems, the user sees all his request withdrawals in YokaiSwap and the explorer shows all his activity correctly. For my part, my test withdrawals can already be seen in pending. If you see it well we can close the issue. 

![Screenshot_20221202-090501_MetaMask](https://user-images.githubusercontent.com/94946624/205247168-01742a74-55ca-4bfb-80e3-b07a0e1a1a8d.jpg)

Thank you!

**Comment by Flouse** [comment]
@alejandroRbit 
Thank you for what you do for the user.
