### ISSUE TITLE
Bug: funds locked in Godwoken v0 legacy withdrawals generated by Safepal

### ISSUE THREAD

**Issue by alejandroRbit** [godwokenrises/light-godwoken#243]
I have a user with the following problem:

Made a CKB withdrawal from L2 Godwoken V0 to L1 Nervos using Safepal CKB Bridge. That is, he did not use the YokaiSwap interface to make the withdrawal, but the Safepal interface. That interface, CKB Bridge, no longer exists today. After many attempts, he managed to activate the withdrawal manually but the funds never arrived at L1 and it disappeared from the Safepal withdrawal history, which makes me think that the withdrawal was not really activated and is still blocked (in the TXID it can be seen that the funds are in a middleware address). The user contacted Safepal support but they have not been able to fix it. He has checked if his withdrawal appears on Godwoken Bridge and YokaiSwap, and it does not appear on the interface.

The problem reminds me a lot of that of this other user. The main difference is that he made the withdrawal through YokaiSwap and not from Safepal CKB Bridge.

https://discord.com/channels/657799690070523914/671648403071172619/1022503232498585670

I thought that perhaps we can apply the same solution as to the other user, and he can finally access his funds.

I have sent you a DM via discord @Flouse with the TXID and the addresses of the user to safeguard his privacy, my tag is AlejandroR # 9014 in discord.

Thank you.

**Comment by Flouse** [comment]
https://bridge.godwoken.io/#/v0/withdrawal/pending 
Godwoken bridge v0 supports unlock legacy(v0) withdrawal cells.

@alejandroRbit Did the user use the right version of Godwoken Bridge?

## Related PR
- https://github.com/godwokenrises/light-godwoken/pull/200

**Comment by Flouse** [comment]
> That is, he did not use the YokaiSwap interface to make the withdrawal, but the Safepal interface. That interface, CKB Bridge, no longer exists today.

## Update
On the asset details page of CKB, Safepal will add an unlock_withdrawal entry for the legacy Godwoken v0 withdrawals.
Waiting for the next version of Safepal.

**Comment by Flouse** [comment]
## Update
The latest Safepal app provides an unlock_withdrawal entry for the legacy Godwoken v0 withdrawals. 🥂 
![image](https://user-images.githubusercontent.com/1297478/213108345-aca025cf-a011-4ca0-a2a4-aa88cfc6f6bf.png)

**Comment by Flouse** [comment]
## Update: The unlock_withdrawal feature in Safepal do not work

One user:
> "When I click on it, I just confirm transaction and nothing happens.
> It doesn’t work even after confirming the withdrawal transaction. I have tried it more than 20 times.
> When I click withdraw and give permission to withdraw, it doesn’t get to the stage where I will sign the transaction 

## Anaysis
existing locked legacy Godwoken v0 withdrawals from Safepal: 1800+
> - Analyzed by https://github.com/godwokenrises/godwoken-tests/pull/227

**Comment by Flouse** [comment]
> ## Update
> The latest Safepal app provides an unlock_withdrawal entry for the legacy Godwoken v0 withdrawals. 🥂 ![image](https://user-images.githubusercontent.com/1297478/213108345-aca025cf-a011-4ca0-a2a4-aa88cfc6f6bf.png)

## The `Unlock Withdrawal` feature works well since Safepal v3.8.2.
