### ISSUE TITLE
Network switching strategy is too aggressive

### ISSUE THREAD

**Issue by ShookLyngs** [godwokenrises/light-godwoken#254]
### The problem
Currently, whenever the current network changes from a supported network to an unsupported network, godwoken-bridge requests to switch the current network to a supported one, which can be too aggressive as it can be triggered even if the user was focusing on other apps.

Maybe when we detect a network change, we should notify and ask the user to switch the network first, instead of requesting the switch directly. An example of the process:
1. Detect if the current network changes to an unsupported network
2. If it does, ask to switch the network via confirm dialog
3. If confirmed, request to switch the network

### Contributors
Thanks to @gpBlockchain @Dawn-githup for pointing out the issue.

**Comment by GitOfJason** [comment]
I want to try it. @ShookLyngs @Flouse
