### ISSUE TITLE
Unable to load token logos under the `cryptologos` domain

### ISSUE THREAD

**Issue by ShookLyngs** [godwokenrises/light-godwoken#278]
For example, this logo url has failed, we might have to look it up:
https://cryptologos.cc/logos/nervos-network-ckb-logo.svg?v=002

**Comment by Flouse** [comment]
> https://cryptologos.cc/logos/nervos-network-ckb-logo.svg?v=002

<img width="479" alt="image" src="https://user-images.githubusercontent.com/1297478/221734163-83bc6526-d840-439b-abf5-5d5bf17871de.png">
It works in my browser.

**Comment by ShookLyngs** [comment]
False alarm, now the connection is normal.
