### ISSUE TITLE
The failed withdrawal transaction will remain in the history record

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#298]
#### Steps to reproduce the behavior:
1.Continuously submitting multiple withdrawal requests.
2.Unprocessed withdrawal requests (e.g. failed over withdrawal) will remain in the history record.

![image](https://user-images.githubusercontent.com/77844990/232746656-8bc25a50-1365-4da9-8f9b-f90a4b7f9c64.png)

Transaction hash： 0x81dd4415e37eee1d7581f1f5e9c18e9a388a9606d8984715cb10d6bcca3a7ad5

**Comment by Flouse** [comment]
# Reproduce the problem
![image](https://user-images.githubusercontent.com/1297478/232945383-396f0f15-cad7-471f-8f4d-0d07b66e2e74.png)

1. I submitted 2 withdrawal requests which contained a `over withdrawal`.
2. A few seconds later, the `over withdrawal` disappeared.
3. But when I refreshed the page or switched between Pending and Completed tabs, the `over withdrawal` came back.

## What is a over withdrawal?
Let's say a user only has 1000 CKB on layer-2, and he requests a 800 CKB withdrawal, and then immediately request another 600 CKB withdrawal. Then we say that 600 CKB withdrawal is an over withdrawal.

## Simple workaround
- https://github.com/godwokenrises/light-godwoken/pull/300

![image](https://user-images.githubusercontent.com/1297478/233249089-618235e3-8ced-4ae5-ab60-3c90d9d37fcf.png)

**Comment by Dawn-githup** [comment]
https://github.com/godwokenrises/light-godwoken/pull/304

**Comment by Dawn-githup** [comment]
304
