### ISSUE TITLE
pending requests will automatically disappear from the pending list and only reappear after the page is refreshed

### ISSUE THREAD

**Issue by Dawn-githup** [godwokenrises/light-godwoken#299]
#### Steps to reproduce the behavior:
1.Submit multiple withdrawal requests.
2.Unprocessed pending requests will automatically disappear from the pending list and only reappear after the page is refreshed.

**Comment by Flouse** [comment]
![image](https://user-images.githubusercontent.com/1297478/232945383-396f0f15-cad7-471f-8f4d-0d07b66e2e74.png)

1. I submitted multiple withdrawal requests which contains a `over withdrawal`.
2. A few seconds later, the `over withdrawal` dispeared.
3. But when I refreshed the page or switched between Pending and Completed tab, the `over withdrawal` came back.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/1297478/232945879-2fe0cf98-63e1-459a-909e-308445aa2ae4.png">

**Comment by Dawn-githup** [comment]
![GIF 2023-4-19 10-27-17](https://user-images.githubusercontent.com/77844990/232951040-5108ed39-62f6-4b39-a701-0bcb7264942c.gif)

**Comment by lee920217** [comment]
Hi Dawn, I tried to reproduce the bug in Chrome and other browsers, but I couldn't replicate the effect shown in the screenshot. Could you please provide some details about the network environment and specific steps to help pinpoint the issue more accurately?

**Comment by lee920217** [comment]
Hi, @Dawn-githup  should be fixed in this [PR](https://github.com/godwokenrises/light-godwoken/pull/310)
