### ISSUE TITLE
[Bug] Failed to withdraw from L2 to L1

### ISSUE THREAD

**Issue by alejandroRbit** [godwokenrises/light-godwoken#314]
A user has reported the following problem when withdrawing from L2 to L1.

Through Godwoken Bridge:
![photo_2023-07-03_13-17-14](https://github.com/godwokenrises/light-godwoken/assets/94946624/55f663a2-2047-4616-ae00-8e8a322cef53)

Through YokaiSwap:
![photo_2023-07-03_13-17-01](https://github.com/godwokenrises/light-godwoken/assets/94946624/ddae9193-fb52-4881-8aa2-71d5b1866a2c)

I myself have tried it on both interfaces and I get the same error. At first I thought it was due to being connected to another network but it seems that this is not the problem, since we have both checked to be connected to Godwoken v1 mainnet (also the swap between tokens works properly).

For more information I have used Metamask wallet on Android.

**Comment by Flouse** [comment]
I just successfully sent a withdrawal request through [Godwoken Bridge](https://bridge.godwoken.io/#/v1/withdrawal), using Metamask browser extension:

> Withdrawal Tx(0x2c08b1885a24137bcef31955f4e734fd22847424daab43d7cd22ec0461c6ab36) has been sent
> Related layer1 tx: https://explorer.nervos.org/transaction/0xe5f8dee2334f8a2598d344aa20cf70bc0248b6bd5207b7087f6bbd4703890160

**Comment by Flouse** [comment]
### And YokaiSwap seems works to me

1. 
![image](https://github.com/godwokenrises/light-godwoken/assets/1297478/60f5385a-b2c9-48b2-aadb-6b19712be896)

2. 
<img width="511" alt="image" src="https://github.com/godwokenrises/light-godwoken/assets/1297478/6c5472bf-78ce-4787-b0e0-ceff8e17f5cb">

3. related layer1 tx: https://explorer.nervos.org/transaction/0xe6043cb7460ef2800518a652d7747c6b4cbfc8aa4ce90b885b00ce6672aae647#2

**Comment by Flouse** [comment]
## Update

One of our test engineer made some tests:
He [can withdraw](https://v1.gwscan.com/account/0x57a8826CcE900d13e3Dc1f8f89Ac73B0BeC70325?tab=bridged) through iOS Metamask, but face the same problem on Android.

So, I think it is a bug of Android Metamask.

**Comment by alejandroRbit** [comment]
The issue seems to only affect Metamask on Android. The withdrawal with Metamask wallet extension on desktop works, so if you have difficulties when withdrawing from L2 to L1 using Android, try doing it in Metamask wallet extension for desktop.
